### ISSUE TITLE
zzstruct.scm fails to compile

### ISSUE THREAD

**Issue by nalck** [jpt4/chanadu#4]
Using the [stalin](http://community.schemewiki.org/?Stalin) compiler, I was returned the following error on zzstuct.scm:

`zzstruct.scm:5:Improper character after sharp sign`.

[Chicken](http://www.call-cc.org/) produced the following:

`Warning: redefinition of extended binding: atom?`

And with [bigloo](http://www-sop.inria.fr/mimosa/fp/Bigloo/):

`File "zzstruct.scm", line 32, character 1458:
#(define (zz-init cls)
#^
*** ERROR:top-level:Parse error
Illegal module form -- (define (zz-init cls) (zz-init-aux cls))`

**Comment by jpt4** [comment]
zzstruct.scm is developed with Guile Scheme, as is the rest of chanadu, and
currently makes no guarantees about cross-implementation portability, of
which type all the errors mentioned are.

In order:
Stalin accuses the #| ... |# block comment style of impropriety, presumably
because it does not support it.

Chicker is warning about the definition of (atom?), which it and Petite
Chez Scheme (among others) have, but Guile does not.

Bigloo's error is the least understandable, since line 32 only has 21
characters, not 1458. However, it would seem to be expecting a module or
other import statement (akin to C header files) as the first line of the
.scm file. Guile also uses a module system, but zzstruct.scm does not
require any.

Regardless of the relevance of the errors to the semantics of the program
as written, zzstruct.scm will shortly be deprecated for zzobj.scm;
multi-implementation testing will remain a lower priority than basic
functionality, but better enthusiastic and early than lackadaisical and
late.

--jpt4
